"""Build constants/homeInsights.ts with daily Did you know tips."""
from __future__ import annotations

from pathlib import Path

# Original wording. No hyphens/dashes in tip text. Stats are round, widely cited
# public health or basic anatomy facts paraphrased (not copied from any source).
TIPS: list[str] = [
    # Epidemiology / big picture
    "About 4 in 5 adults get back pain at least once in their life.",
    "Low back pain is the leading cause of disability worldwide.",
    "Over 600 million people live with low back pain around the world.",
    "Back pain cases may rise past 800 million by mid century as populations age.",
    "Most people get back pain at some point, including younger adults.",
    "Back pain peaks for many people in their early to mid 50s.",
    "Women report low back pain a bit more often than men.",
    "Repeat episodes of back pain get more common as people age.",
    "Among health problems, back pain is where rehab can help the most people.",
    "Most back pain is not caused by a serious disease or fracture.",
    "A large share of doctor visits for pain involve the back.",
    "Back pain is one of the top reasons people miss work worldwide.",
    "Kids and teens can get back pain too, especially with long hours of sitting.",
    "First time back pain often settles within a few weeks.",
    "Only a small share of back pain becomes long lasting.",
    "Recurrence is common even after a good recovery.",
    "Back pain can start at almost any age.",
    "Older adults feel the disability impact of back pain the most.",
    "Office workers and heavy laborers both report a lot of back pain.",
    "Back pain costs societies hundreds of billions each year in care and lost work.",

    # Movement / rehab principles
    "Most new back pain eases within a few weeks when you keep moving gently.",
    "Long bed rest used to be common advice. Gentle activity is usually better now.",
    "A short daily walk is one of the simplest ways to keep a sore back moving.",
    "For rehab, showing up often beats going hard once in a while.",
    "Many long term cases improve when people keep a steady movement habit.",
    "Light activity during a flare is often safer than waiting until pain is gone.",
    "Standing up and changing positions often beats holding one posture all day.",
    "Your back is built to bend and carry load within reason.",
    "Strength work with good form helps protect the spine over time.",
    "Stronger hips and glutes help take load off your lower back.",
    "Your core is more than abs. Deep trunk muscles help steady the spine.",
    "Hamstring tightness can tug on the pelvis and bother the lower back.",
    "Breathing slow and easy can lower muscle guarding around a sore back.",
    "A quick stretch break each hour can ease desk related tightness.",
    "Sitting for hours without a break is a common trigger for stiffness.",
    "Pain that comes and goes is common. A flare does not always mean new damage.",
    "Heat can ease tight back muscles for some people after activity.",
    "Cold packs can calm a hot, irritable area for some people early on.",
    "Gentle mobility work can feel better than forcing a deep stretch.",
    "Slow controlled reps often beat bouncing or rushing through moves.",
    "You do not need perfect posture all day. Varied posture matters more.",
    "A little discomfort while moving can be okay if it settles after.",
    "Sharp new pain with numbness or weakness is a reason to get checked.",
    "Building tolerance to daily tasks is a core goal of rehab.",
    "Balance work helps the body control the spine during real life moves.",
    "Hip hinge practice teaches your back and hips to share the load.",
    "Bird dog style moves train control without heavy loading.",
    "Glute bridges wake up muscles that support the pelvis and spine.",
    "Dead bugs teach the trunk to stay steady while the limbs move.",
    "Side planks train the muscles that keep the spine from side bending.",
    "Cat cow style motion can ease morning stiffness for many people.",
    "McKenzie style press ups help some people who feel better with extension.",
    "Figure four stretches target hip rotators that can tug on the low back.",
    "Open book rotations help the mid back move so the low back works less.",
    "Childs pose can feel soothing when the low back wants gentle flexion.",
    "Suitcase carries train the trunk to resist side bending under load.",
    "Split squats build single leg strength that supports walking and stairs.",
    "Rows strengthen the upper back so the shoulders sit with less strain.",
    "Hip flexor stretches can help if long sitting keeps the front hips tight.",
    "Thoracic extension over a chair can free a stiff mid back.",
    "Clamshells wake up side hip muscles that stabilize the pelvis.",
    "Single leg bridges raise the challenge once two leg bridges feel easy.",
    "Rest days still count. Tissue and nerves adapt between sessions.",
    "Sleep and sessions work together. Recovery is part of the plan.",
    "Tracking pain before and after sessions helps you spot useful patterns.",
    "Small weekly progress adds up more than rare heroic workouts.",
    "If a move spikes pain for hours, scale it down next time.",
    "Pain during a set that fades within a day is often workable.",
    "Form first, then load. Adding weight on sloppy form raises risk.",
    "Breathing out on effort can keep the trunk braced without straining.",
    "Bracing lightly for lifts is useful. Holding a hard brace all day is not.",
    "Walking after sitting is a simple reset for a stiff spine.",
    "Stairs and hills challenge the hips in ways flat walks do not.",
    "Swimming or water walking can unload the spine while you move.",
    "Cycling can be friendly if the bike fit keeps you from rounding hard.",
    "Yoga style flows help some people. Skip poses that spike your pain.",
    "Pilates style control work overlaps a lot with modern back rehab.",
    "Bodyweight strength is enough for many people early in rehab.",
    "Bands are a gentle way to add load without heavy equipment.",
    "Dumbbells let you train hinges and squats with easy progression.",
    "Machines can feel safer early on because the path is guided.",
    "Free weights teach control that transfers well to daily life.",
    "Warm ups need only a few minutes of easy motion to count.",
    "Cool downs are optional. Consistency of the main work matters more.",
    "Morning sessions suit some people. Evening sessions suit others.",
    "Same time each day makes the habit easier to keep.",
    "Missed a day? Start again tomorrow. One gap rarely ruins progress.",
    "Two short sessions can beat one long one if life is busy.",
    "Pair rehab with a daily cue like coffee or brushing your teeth.",
    "Progress photos and pain scores beat guessing how you feel.",
    "Confidence in movement often returns before pain fully leaves.",
    "Fear of motion can keep pain around even when tissues are ready.",
    "Graded exposure means slowly reintroducing moves you have been avoiding.",
    "Lifting mechanics matter, but so does how often you practice them.",
    "Picking up a toddler uses the same hinge pattern as a gym deadlift.",
    "Carrying groceries on one side is a real world side plank.",
    "Getting off the floor trains strength you use at home every week.",
    "Gardening and housework can be rehab if you pace them.",
    "Travel days are high risk for stiffness. Plan walk breaks.",
    "Long drives: stop, stand, and walk a few minutes every hour or two.",
    "Flights: aisle walks and ankle pumps help more than sitting still.",
    "New shoes with soft cushion can change how load hits your back.",
    "Uneven sidewalks challenge balance muscles that support the spine.",

    # Anatomy
    "Your spine has 24 movable vertebrae from your neck to your lower back.",
    "Counting the fused bones below, adults have 33 vertebral segments in total.",
    "There are 7 neck vertebrae, 12 mid back, and 5 lower back.",
    "The sacrum is five fused vertebrae that lock into the pelvis.",
    "The coccyx is the small tailbone at the very end of the spine.",
    "Each pair of vertebrae forms a joint that can tip, slide, and rotate a little.",
    "Facet joints on the back of the spine guide and limit motion.",
    "Spinal discs sit between vertebrae like soft spacers and shock pads.",
    "A disc has a tough outer ring and a softer gel like center.",
    "Spinal discs get most of their nutrients from movement, not from blood flow.",
    "The soft pads between vertebrae are mostly water when you are young.",
    "You are a bit taller in the morning. Discs lose a little fluid height by night.",
    "Discs thin a little with age. That is common, not always painful.",
    "The spinal cord runs through a bony canal protected by the vertebrae.",
    "Nerve roots exit between vertebrae and travel into the arms or legs.",
    "Sciatica style pain often follows a nerve path into the leg.",
    "Not every leg symptom means a disc is pressing on a nerve.",
    "Ligaments stitch vertebrae together and limit extreme motion.",
    "The anterior longitudinal ligament runs down the front of the spine.",
    "The posterior longitudinal ligament runs along the back of the vertebral bodies.",
    "Multifidus muscles are small deep stabilizers along the spine.",
    "Erector spinae are the long muscles that help you stand tall.",
    "Quadratus lumborum links the ribs, spine, and pelvis on each side.",
    "Psoas muscles connect the spine to the thighs and help lift the legs.",
    "Glute max is a powerhouse for hip extension and upright posture.",
    "Glute med keeps the pelvis level when you stand on one leg.",
    "Latissimus dorsi links the arm to the low back and pelvis.",
    "The thoracolumbar fascia is a tough sheet that ties back muscles together.",
    "Ribs attach to the 12 mid back vertebrae and limit twisting there.",
    "The neck is the most mobile region of the spine.",
    "The lower back is built more for load bearing than for big twists.",
    "The mid back helps rotate the trunk so the low back can stay calmer.",
    "Natural spine curves include a neck arch, mid back round, and low back arch.",
    "A gentle low back arch is normal. Flat or extreme curves are just variations.",
    "The pelvis and low back move as a team in almost every step you take.",
    "Sacroiliac joints link the sacrum to each side of the pelvis.",
    "Sacroiliac joints move only a tiny amount in healthy adults.",
    "Intervertebral foramina are the bony windows where nerves exit.",
    "End plates are thin bone and cartilage layers that feed the discs.",
    "Vertebral bodies are the thick front blocks that carry most of your weight.",
    "Spinous processes are the bumps you feel down the middle of your back.",
    "Transverse processes are side wings where muscles and ligaments attach.",
    "The atlas is C1 and holds up the skull.",
    "The axis is C2 and lets the head turn side to side.",
    "Lumbar vertebrae are the largest movable bones in the spine.",
    "Cervical vertebrae have holes for arteries that travel toward the brain.",
    "Thoracic vertebrae have seats where ribs attach.",
    "Nucleus pulposus is the soft center of a disc.",
    "Annulus fibrosus is the layered outer ring of a disc.",
    "Disc rings are arranged in angled layers for strength.",
    "Healthy discs can handle a lot of compression when they get time to recover.",
    "Twisting under a heavy load is harder on discs than a clean hinge.",
    "The spine can flex, extend, side bend, and rotate in small combined ways.",
    "No single perfect curve fits every body. Fit and comfort vary.",
    "Bones remodel slowly with training load, just like muscle does.",
    "Tendons and ligaments adapt slower than muscle, so progress patiently.",
    "Muscle can gain strength in weeks. Tendon changes often take months.",
    "Cartilage likes cycles of load and unload more than constant pressure.",
    "Synovial fluid lubricates facet joints when you move.",
    "Joint capsules wrap the facet joints and hold lubricating fluid in place.",
    "Proprioceptors in joints and muscles tell the brain where the spine is.",
    "Better body awareness often comes along with better control in rehab.",

    # Physiology / pain science (careful, general)
    "A rough night of sleep can make pain feel worse the next day.",
    "Stress often shows up as muscle tension in the neck and back.",
    "Pain is an alarm system. Louder alarms do not always mean more damage.",
    "The brain can turn pain volume up or down based on sleep, mood, and stress.",
    "After an injury, nerves can stay sensitive for a while even as tissues heal.",
    "Imaging can show disc bulges in people who feel no pain at all.",
    "Many pain free adults have age related spine changes on scans.",
    "A scan finding is a clue, not always the full story of your pain.",
    "Inflammation early after a strain is part of normal healing.",
    "Blood flow rises in working muscle and helps clear metabolic waste.",
    "Warm muscles stretch and contract more easily than cold ones.",
    "Cortisol and adrenaline from stress can keep muscles braced.",
    "Endorphins from steady exercise can briefly dull pain signals.",
    "Hydration supports disc fluid content, but chugging water is not a cure.",
    "Breathing into the belly can reduce neck and shoulder bracing.",
    "Jaw clenching often pairs with neck and upper back tension.",
    "Eye strain from screens can lead to a forward head posture.",
    "Forward head posture makes neck muscles work harder to hold you up.",
    "A backpack worn on one shoulder loads one side of the spine more.",
    "Phone use with a bent neck adds a surprising amount of leverage on cervical joints.",
    "The head weighs about as much as a bowling ball for your neck muscles.",
    "Gravity loads the spine all day while you sit or stand.",
    "Lying down unloads the spine and lets discs rehydrate overnight.",
    "Side sleeping with a pillow between the knees can comfort some backs.",
    "Stomach sleeping can force the neck to twist for hours.",
    "A mattress that keeps you roughly level often beats a super soft sink.",
    "Pillow height should keep the neck in line with the mid back.",
    "Nighttime bathroom trips that cut sleep can raise next day pain.",
    "Caffeine late in the day can fragment sleep that your back needs.",
    "Alcohol can reduce sleep quality even if it helps you nod off.",
    "Regular meal timing supports energy for rehab sessions.",
    "Protein helps repair muscle after strength work.",
    "Vitamin D and bone health matter for the skeleton that holds you up.",
    "Smoking is linked with a higher chance of back pain lasting longer.",
    "Nicotine narrows blood vessels that feed spinal structures.",
    "Carrying extra body weight raises stress on the lower spine over time.",
    "Belly weight shifts the center of mass and can increase low back demand.",
    "Heavy lifting and awkward work postures raise the risk of back pain.",
    "Whole body vibration from some vehicles is linked with more back complaints.",
    "Cold weather does not cause arthritis, but it can make stiffness feel worse.",
    "Barometric swings make some people notice joint aches more.",
    "Menstrual cycles can change pain sensitivity for some women.",
    "Growth spurts can temporarily change posture and muscle tightness in teens.",
    "Pregnancy shifts the center of gravity and increases low back demand.",
    "After pregnancy, gradual return to core and hip strength is common advice.",
    "Bone density peaks in early adulthood and declines later without loading.",
    "Impact and strength training help bones stay denser over the years.",
    "Balance declines with age unless you practice it on purpose.",
    "Fall risk and back fear can feed each other in older adults.",
    "Vision and foot feeling both feed the balance system that protects the spine.",

    # Lifestyle / ergonomics / daily life
    "Desk height that lets elbows bend near 90 degrees reduces shoulder shrug.",
    "Screen tops near eye level cut the urge to crane the neck down.",
    "A laptop on a low table often means more neck bend. Raise the screen if you can.",
    "External keyboard and mouse let a laptop screen sit higher.",
    "Feet flat on the floor or a footrest beat dangling legs for long sits.",
    "A chair that lets you plant your feet and rest your back is enough for most.",
    "Lumbar pillows help some people and bother others. Comfort rules.",
    "Perching on the front edge of a chair for hours tires the back muscles.",
    "Crossing legs for a long time can tilt the pelvis unevenly.",
    "Wallet sat on in a back pocket can hike one side of the pelvis.",
    "Standing desks help when you switch positions, not when you stand frozen.",
    "Anti fatigue mats make long standing shifts easier on the legs and back.",
    "Kitchen counters at a usable height reduce constant forward bending.",
    "Raise the laundry basket so you are not folding on the floor all day.",
    "Golfers lift for light objects: hand on a thigh, hinge, then stand.",
    "Keep heavy objects close to your body when you carry them.",
    "Split a heavy load into two lighter trips when you can.",
    "Pushing a cart usually beats pulling it for spinal load.",
    "A backpack with two straps beats a single shoulder strap bag.",
    "Tighten backpack straps so the load sits close to your back.",
    "Kids backpacks should stay light relative to body weight.",
    "Phone on a stand during long calls saves neck bend.",
    "Earbuds or a headset beat cradling a phone on one shoulder.",
    "Reading in bed with stacked pillows can crank the neck for hours.",
    "TV watching reclined with support can be easier than slumping on soft cushions.",
    "Gaming sessions need the same break rules as desk work.",
    "Musicians often get neck and back strain from asymmetrical setups.",
    "Hairdressers and dentists load one side with sustained reach postures.",
    "Warehouse work mixes lifting, twisting, and repetition. Pace and technique matter.",
    "Nurses and caregivers do frequent patient transfers that challenge the back.",
    "Parents lifting car seats and cribs need a solid hinge habit.",
    "Dog walking that jerks one arm can torque the trunk. A shorter leash helps.",
    "Shoveling snow is a classic back strain setup. Small scoops and pivots help.",
    "Raking and vacuuming are repetitive reaches. Switch hands and take pauses.",
    "Moving day: lift with partners and use dollies more than hero strength.",
    "DIY projects on the floor: kneel on a pad and change positions often.",
    "Painting ceilings loads the neck into extension. Use roller poles and breaks.",
    "Gaming or editing in a dark room can make you crane toward the screen.",
    "Bright, well placed light reduces the forward lean toward the display.",
    "Blue light late at night can delay sleep that helps recovery.",
    "A consistent bedtime supports the overnight disc rehydration window.",
    "Weekend warrior spikes in activity are a common way to stir up the back.",
    "Ramp mileage or gym volume by small weekly jumps, not sudden doubles.",
    "New sport, new loads. Give tissues a few weeks to adapt.",
    "Cleats and high heels change pelvic tilt and can bother some backs.",
    "Worn out running shoes alter force through the legs into the spine.",
    "Orthotics help some foot mechanics and do nothing special for others.",
    "Flat feet or high arches are variations. Symptoms matter more than labels.",
    "Tight calves can change gait and the way load reaches the back.",
    "Ankle stiffness often shows up as extra motion demand higher up the chain.",
    "Hip stiffness can force the low back to twist more during steps.",
    "Mid back stiffness can push extra motion into the neck or low back.",
    "Shoulder tightness can pull the upper spine into a rounded posture.",
    "Jaw and neck tension often travel together.",
    "Breath holding during hard effort spikes pressure in the trunk.",
    "Gentle humming or long exhales can downshift a braced nervous system.",
    "A short outdoor walk in daylight can lift mood and ease pain perception.",
    "Social support during rehab predicts who sticks with the plan.",
    "People who expect to improve often report better function over time.",
    "Catastrophizing about pain is linked with longer recovery in research.",
    "Simple coping phrases beat doom scrolling about worst case spine stories.",
    "Most disc issues improve without surgery.",
    "Surgery helps select cases. Many people recover with guided exercise alone.",
    "Second opinions are reasonable before any elective spine procedure.",
    "Red flags like fever with back pain or loss of bladder control need urgent care.",
    "Unexplained weight loss with back pain also deserves a medical check.",
    "Pain after a bad fall or car crash should be evaluated.",
    "Night pain that always wakes you may need a clinician visit.",
    "Progressive leg weakness is not a wait and see symptom.",
    "Saddle numbness is an emergency warning sign.",
    "For ordinary back pain, early imaging rarely changes the first plan.",
    "Guidelines often favor staying active over routine early scans.",
    "Hands on therapy can feel good. Lasting gains usually need your own exercise.",
    "Massage may ease muscle tone for a while without fixing the root habit.",
    "Chiropractic adjustments help some people short term. Pair them with exercise.",
    "Acupuncture helps some people with pain. Results vary widely.",
    "TENS units can distract pain signals for short windows of relief.",
    "Over the counter pain meds can help you move. Follow label and clinician advice.",
    "Muscle relaxants make some people sleepy and are not a long term fix.",
    "Opioids are generally not first line for ordinary mechanical back pain.",
    "Injections are a tool for select cases, not a stand alone cure.",
    "Belts and braces can help briefly. Relying on them all day can weaken control.",
    "Kinesiology tape may change how something feels more than how it heals.",
    "Foam rolling can reduce perceived tightness for a short time.",
    "Lacrosse ball work on the glutes can ease referral into the low back.",
    "Stretching cold tissues hard is a common way to irritate things.",
    "Move first, then stretch soft tissue that still feels limited.",
    "Strength often reduces the need for endless stretching.",
    "Flexibility without control does not protect the spine much.",
    "Control through a range is more useful than flopping to end range.",
    "Isometrics can calm pain for some people while still training muscle.",
    "End range lifts are advanced. Own the middle range first.",
    "Tempo work (slow lowers) builds control with lighter loads.",
    "Pausing at the hardest point of a move teaches ownership of that position.",
    "Unilateral training exposes side to side gaps that bilateral work can hide.",
    "Training the weaker side first can restore balance over weeks.",
    "Grip strength often limits carries before the back does.",
    "Farmers carries build trunk endurance that shows up in daily life.",
    "Loaded walks are underrated rehab for many backs.",
    "Sled pushes train drive through the hips with little spinal shear.",
    "Step ups mimic stairs and build useful single leg power.",
    "Sit to stand practice from a chair is real life strength training.",
    "Floor to stand transitions matter for independence as we age.",
    "Crawling patterns wake up cross body coordination.",
    "Marching in place is a tiny dose of hip flexor and core control.",
    "Heel raises keep the calves contributing to a springy walk.",
    "Toe yoga and foot strength support the base the spine stands on.",
    "Wide stance work feels more stable early in rehab for some people.",
    "Narrow stance and split stance come later as control improves.",
    "Barefoot work on safe floors can wake up foot muscles.",
    "Soft sand walks load the legs more and may tire the back sooner.",
    "Uphill walks bias the glutes. Downhills load the knees and quads more.",
    "Nordic walking poles can unload the spine a little on longer walks.",
    "Hiking poles help on uneven trails where balance matters.",
    "Dancing trains rotation and rhythm in a way machines rarely do.",
    "Playful movement lowers fear for some people stuck in careful patterns.",
    "Sports that mix sprinting and twisting need a solid base of control first.",
    "Return to sport is a ladder, not a switch you flip overnight.",
    "Kids in sport need variety. Same motion year round raises overuse risk.",
    "Coaches who praise mechanics over volume help young spines.",
    "Growth plate areas in teens need extra care with heavy loading.",
    "Masters athletes recover slower and need more space between hard days.",
    "Deload weeks every month or two help many training plans stick.",
    "Pain after a new PR is feedback. Adjust the next session.",
    "Ego lifting is a classic gym back story. Leave a rep or two in the tank.",
    "A training log beats memory when pain patterns are subtle.",
    "Share useful patterns with your clinician so care stays specific.",
    "Second flare in a month means scale load, not abandon movement.",
    "Boring basics done for months beat fancy routines done for days.",
    "The best rehab plan is the one you will still do next month.",
    "Your spine loves variety: walk, hinge, carry, and breathe.",
    "Motion is lotion for many stiff backs.",
    "Stillness for hours is a bigger enemy than imperfect form for a minute.",
    "You can train while sore if soreness is mild and improving day to day.",
    "You should pause and get help if pain is severe, spreading, or new and scary.",
    "Recovery is rarely a straight line. Wiggles in the chart are normal.",
    "Good days are for building capacity. Bad days are for gentle maintenance.",
    "Celebrate function wins like tying shoes or sitting through a movie.",
    "Pain scores dropping one point still count as progress.",
    "Sleeping through the night again is a rehab milestone.",
    "Returning to a hobby you paused is a bigger win than any gym number.",
    "Teaching a family member your hinge cue helps you learn it deeper.",
    "Community classes add accountability that solo plans sometimes lack.",
    "Digital programs work best when you still listen to your own symptoms.",
    "No app replaces urgent care when red flags appear.",
    "Curiosity about how your body responds beats frustration on hard days.",
    "Patience is a training skill just like strength.",
    "Your future self benefits from the short session you almost skipped.",
    "Done is better than perfect when the choice is move or skip.",
    "The spine is tough living tissue. It adapts when you give it smart work.",
    "Bones, discs, and muscles all respond to the loads you repeat most.",
    "What you do most days shapes your back more than what you do once.",
    "Small daily deposits of movement beat rare marathon efforts.",
    "You are allowed to start easier than your pride wants.",
    "Easy starts make harder work possible later.",
    "A calm breath before a lift is a free performance tool.",
    "Soft knees when you stand can reduce locked joint strain.",
    "Unlocking the knees is not slouching. Soft and tall can coexist.",
    "Ribs stacked over pelvis is a simple cue for a steady trunk.",
    "Exhale to feel the lower ribs settle without sucking the belly in hard.",
    "Think long spine more than stiff spine.",
    "Reach the crown of the head up and the sit bones down for easy length.",
    "Shoulders rest on the ribcage. They do not need to hike toward the ears.",
    "Let the shoulder blades glide instead of pinning them in one place.",
    "Eyes on the horizon during carries help you avoid looking down into a slump.",
    "Packing the neck gently (chin slight nod) can quiet upper trap noise.",
    "A light smile and loose jaw are underrated tension checks.",
    "Shake out the arms between sets to drop leftover bracing.",
    "Walk a lap between heavy efforts instead of collapsing into a deep slump.",
    "Hydrate around workouts. Extreme water loading is unnecessary for most.",
    "Electrolytes matter more in long sweaty sessions than in short rehab sets.",
    "Sunlight and walking pair well as a morning reset.",
    "Evening wind down without screens helps the overnight repair window.",
    "A 10 minute walk after dinner aids blood sugar and spinal motion alike.",
    "Family walks turn rehab into something you barely notice doing.",
    "Dog owners get built in walking cues if they keep the pace steady.",
    "Music with a steady beat can make walks and mobility feel shorter.",
    "Timers for desk breaks beat relying on willpower alone.",
    "Habit stacking works: after I close the laptop, I stand and stretch.",
    "Environment design beats motivation. Put your mat where you see it.",
    "Lay out workout clothes the night before to cut friction.",
    "Short programs you finish build trust. Endless programs get abandoned.",
    "Six weeks of steady work is long enough to notice real change for many.",
    "Twelve weeks is a fair window to judge a strength focused plan.",
    "Year long habits matter more than any single program brand.",
    "Your back did not get sensitive in a day. Give recovery a fair runway.",
    "Tissue healing timelines are weeks to months, not hours.",
    "Scar tissue remodels with gradual load. Rushing it often backfires.",
    "Swelling after a new stimulus can be adaptation, not failure.",
    "Delayed soreness peaks a day or two after novel training.",
    "Soreness that shrinks each week means you are adapting.",
    "Soreness that climbs each week means you need more recovery.",
    "Rest is a training tool. So is light movement on off days.",
    "Active recovery walks often beat pure couch time for stiffness.",
    "Sauna or warm showers can relax muscle tone for some people.",
    "Ice after acute spikes can numb and settle irritable tissue.",
    "Contrast of warm and cool is optional. Use what your body likes.",
    "Listen to symptoms for 24 hours after a session to guide the next dose.",
    "Green light: mild symptoms that settle fast. Keep going.",
    "Yellow light: symptoms that linger into the next day. Adjust down.",
    "Red light: sharp, spreading, or scary symptoms. Stop and get advice.",
    "Traffic light dosing keeps you training without guessing every time.",
    "Partners and coaches help when you cannot judge your own effort.",
    "Video yourself hinging once. The mirror lies less than you think.",
    "A stick on the back is an old school cue for keeping a long spine in hinges.",
    "Wall angels teach open upper back motion without equipment.",
    "Doorway pec stretches can free a rounded upper posture.",
    "Chin tucks strengthen deep neck flexors that posture work often misses.",
    "Y raise and T raise patterns wake up lower and mid traps.",
    "Face pulls train the rear shoulders that desk life neglects.",
    "Farmer and suitcase variations cover both even and uneven loading.",
    "Half kneeling positions teach the pelvis to stay quiet while you move.",
    "Tall kneeling removes the ankles so you can focus on trunk control.",
    "Supine moves cut gravity and are a gentle entry when standing is tough.",
    "Quadruped moves add a bit of load while staying friendly for many backs.",
    "Standing moves transfer best to life because life happens standing.",
    "Mix positions across a week so tissues see different demands.",
    "Variety within a plan still needs repetition to build skill.",
    "Skill, capacity, then lifestyle. That order keeps progress sane.",
    "Capacity means how much you can do before symptoms climb.",
    "Raising capacity is the quiet goal behind most good rehab plans.",
    "Life demands should fit under your capacity with a little room to spare.",
    "When life spikes above capacity, flares are more likely.",
    "After a flare, rebuild capacity with smaller steps than your pride wants.",
    "Flares fade faster when you keep some safe movement going.",
    "Complete rest after ordinary flares often slows the return to normal.",
    "Work with a licensed clinician if pain keeps you from basic daily tasks.",
    "Physical therapists are trained to dose movement for irritable backs.",
    "Primary care can rule out serious causes when symptoms are unclear.",
    "Emergency care is for red flags, not for every ordinary ache.",
    "Home programs succeed when the dose fits your real calendar.",
    "Ten honest minutes count. You do not need a perfect hour.",
    "If you hate a move, ask for a swap that trains the same idea.",
    "Enjoyment predicts adherence better than biomechanical perfection.",
    "Curious, calm practice beats grim, fearful practice.",
    "Your spine is not glass. Treat it like the strong, adaptable structure it is.",
]

def main() -> None:
    # Deduplicate while preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for tip in TIPS:
        if tip in seen:
            continue
        seen.add(tip)
        unique.append(tip)

    bad = [t for t in unique if any(ch in t for ch in "-–—")]
    if bad:
        raise SystemExit(f"Dashes found in {len(bad)} tips, e.g.: {bad[0]!r}")

    root = Path(__file__).resolve().parents[1]
    out = root / "constants" / "homeInsights.ts"
    lines = [
        "// Daily home \"Did you know\" tips. One tip per local calendar day.",
        "// getDailyInsightIndex wraps to 0 when the list ends (loops forever).",
        "// REMINDER: Expand before users notice repeats. Unique days = HOME_INSIGHTS.length.",
        "",
        "export const HOME_INSIGHTS: readonly string[] = [",
    ]
    for tip in unique:
        escaped = tip.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  '{escaped}',")
    lines.append("];")
    lines.append("")
    lines.append("/** One insight per local calendar day. Wraps to the start when exhausted. */")
    lines.append("export function getDailyInsightIndex(date = new Date()): number {")
    lines.append("  const count = HOME_INSIGHTS.length;")
    lines.append("  if (count === 0) return 0;")
    lines.append("  const localDay = Math.floor(")
    lines.append("    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000,")
    lines.append("  );")
    lines.append("  return ((localDay % count) + count) % count;")
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(unique)} tips to {out}")


if __name__ == "__main__":
    main()
